// Copyright 2022 The Oak Authors.

#ifndef OAK_COMMON_ASIO_WRAPPER_H_
#define OAK_COMMON_ASIO_WRAPPER_H_

#define ASIO_STANDALONE 1

#define ASIO_NO_DEPRECATED 1
#define ASIO_USE_TS_EXECUTOR_AS_DEFAULT 1
#define ASIO_NO_DYNAMIC_BUFFER_V1 1

#ifndef NODEBUG
# define ASIO_ENABLE_BUFFER_DEBUGGING 1
# define ASIO_ENABLE_HANDLER_TRACKING 1
#else
# define ASIO_DISABLE_BUFFER_DEBUGGING 1
# define ASIO_ENABLE_HANDLER_TRACKING 1
#endif

#define ASIO_NO_TYPEID 1
#define ASIO_DISABLE_VISIBILITY 1

#include "asio.hpp"  // NOLINT

#endif  // OAK_COMMON_ASIO_WRAPPER_H_
